---
title: "WECARE only PCA"
author: "AL"
date: "06/10/2020"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

# Summary

PCA for wecare-only (b37) wes dataset

<style>
pre{
  overflow-x: auto;
}
pre code{
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r echo=F}

options(width=999)

```

# Start section

```{r}

Sys.time()
gc()

rm(list=ls())
base_folder <- "/rds/project/erf33/rds-erf33-medgen"
project_folder <- file.path(base_folder,"users/alexey/wecare/reanalysis_wo_danish_2020")
data_folder <- file.path(project_folder,"data","s05_pca")
scripts_folder <- file.path(project_folder,"scripts","s05_pca")
setwd(scripts_folder)

library(bigsnpr) # for bed_autoSVD() and bed()
library(bigutilsr) # for prob_dist() and tukey_mc_up() for outlier detection
library(hexbin) # for plotting svd loadings
library(ggplot2)
library(dplyr)

NCORES <- 5 # 6 cores were requested in sintr
#NCORES <- nb_cores() doesnt work on cluster
 
```

# Read bed-bim-fam file-set

```{r}

# Location of bed file
bed_file <- file.path(data_folder,"s05_relatedness_check","wecare_biallelic_snps_autosomal_common_norel.bed")

# Read (=attach?) data
wecare.bed <- bed(bed_file) # bigsnpr::bed
wecare.bed

# Explore wecare.bed
attributes(wecare.bed)
str(wecare.bed)

wecare.bed$bedfile
wecare.bed$address

# Clean-up
rm(bed_file)

```

# Phenotypes

```{r}

# fam file
wecare_fam.df <- wecare.bed$fam
dim(wecare_fam.df)
head(wecare_fam.df)

# Phenotypes from external file
load(file.path(base_folder,"users","alexey","wecare","reanalysis_wo_danish_2020","data","s04_add_phenotypes","s02_selected_phenotypes.RData"))

dim(phenotypes.df)
colnames(phenotypes.df)

# Merge fam-file and phenotypes from external file 
wecare_phenotypes.df <- left_join(wecare_fam.df, phenotypes.df,
                                  by=c("sample.ID"="wes_id"))
dim(wecare_phenotypes.df)
colnames(wecare_phenotypes.df)

# Make sure that dplyr::left_joint hasnt changed the order of samples
sum(wecare_phenotypes.df$sample.ID != wecare_fam.df$sample.ID)

# Clean-up
rm(phenotypes.df)

```

# Variants

```{r}

# map file
wecare_map.df <- wecare.bed$map
dim(wecare_map.df)
head(wecare_map.df)

# make simple counts 
wecare_maf.df <- bed_MAF(wecare.bed)
dim(wecare_maf.df)
head(wecare_maf.df)

# merge map file with the counts
variants.df <- cbind(wecare_map.df,wecare_maf.df)
dim(variants.df)
head(variants.df)

# Variants with AF(ref) < AF(alt)
x <- variants.df$ac != variants.df$mac
sum(x)
head(variants.df[x,])

# Clean-up
rm(x, wecare_map.df, wecare_maf.df)

```

# Calculate PCA

Takes care about LD etc.  
See ?plot.big_SVD for plotting svd objets.  

```{r}

# bigsnpr::bed_autoSVD, Default k = 10
wecare.svd <- bed_autoSVD(wecare.bed, ncores = NCORES) 

# Variants not in LD (detected by clumping during autoSVD)
vars_not_in_LD <- attr(wecare.svd, "subset")
length(vars_not_in_LD)

#attributes(wecare.svd)
str(wecare.svd)

# Eigenvalues
length(wecare.svd$d)
wecare.svd$d
plot(wecare.svd) # default type="screeplot" see ?plot.big_SVD  

# Eigenvectors
dim(wecare.svd$u)
head(wecare.svd$u)

# PCA summary (for PCs from 1 to 20)
plot(wecare.svd,type = "scores",scores=1:10,coeff=0.4)

# Loadings
dim(wecare.svd$v)
head(wecare.svd$v)

# Loadings summary (for PCs from 1 to 20)
plot(wecare.svd,type="loadings",loadings=1:10,coeff=0.4)

```

# Detailed PCA plots

```{r}

plot(wecare.svd, type = "scores") +
     aes(color = wecare_phenotypes.df$cc == 1) +
     labs(title = NULL, color = "Case")

plot(wecare.svd, type = "scores", scores=3:4) +
     aes(color = wecare_phenotypes.df$cc == 1) +
     labs(title = NULL, color = "Case")

plot(wecare.svd, type = "scores", scores=5:6) +
     aes(color = wecare_phenotypes.df$cc == 1) +
     labs(title = NULL, color = "Case")

plot(wecare.svd, type = "scores", scores=7:8) +
     aes(color = wecare_phenotypes.df$cc == 1) +
     labs(title = NULL, color = "Case")

plot(wecare.svd, type = "scores", scores=9:10) +
     aes(color = wecare_phenotypes.df$cc == 1) +
     labs(title = NULL, color = "Case")

```

# Selecting outliers 

```{r}

# Eigenvectors
U <- wecare.svd$u

# Measure(s) of "outlieness"  
prob <- prob_dist(U, ncores=NCORES) # bigutilsr::prob_dist
S <- prob$dist.self / sqrt(prob$dist.nn) # alternatively: test$dist.self / test$dist.nn ?
tukey_threshold <- tukey_mc_up(S) # bigutilsr::tukey_mc_up

# Histogram by "outlieness" score
ggplot() +
  geom_histogram(aes(S), color = "black", fill = "blue", alpha = 0.3) +
  theme_bigstatsr() +
  geom_vline(xintercept=tukey_threshold, colour="red") +
  labs(x = "Statistic of outlierness (S)", y = "Frequency (sqrt-scale)")

# No outliers detected
sum(S >= tukey_threshold)

# Clean-up
rm(U,prob,S,tukey_threshold,NCORES)

```

# Add PCs to phenotypes

```{r}

eigenvectors.mx <- wecare.svd$u
colnames(eigenvectors.mx) <- 
  c("pc1","pc2","pc3","pc4","pc5","pc6","pc7","pc8","pc9","pc10")

phenotypes.df <- cbind(wecare_phenotypes.df, eigenvectors.mx)
dim(phenotypes.df)
colnames(phenotypes.df)

# Make sure that the order of samples hasnt changed
sum(phenotypes.df$sample.ID != wecare_fam.df$sample.ID)

# Check consistency with the previous eigenvectors from WES
plot(phenotypes.df$eig1_wecare,phenotypes.df$pc1,main="PC1: new vs old WES")
plot(phenotypes.df$eig2_wecare,phenotypes.df$pc2,main="PC2: new vs old WES")

# Check consistency with the previous eigenvectors from GWAS
plot(phenotypes.df$eig1_gwas,phenotypes.df$pc1,main="PC1: new WES vs GWAs")
plot(phenotypes.df$eig2_gwas,phenotypes.df$pc2,main="PC2: new WES vs GWAs")

# Clean-up
rm(wecare_phenotypes.df, eigenvectors.mx, wecare_fam.df)

```

# Save results

```{r}

save.image(file.path(data_folder,"s12_calculate_PCs.RData"))
save(phenotypes.df,file=file.path(data_folder,"s12_phenotypes_with_PCs.RData"))

```

# End section

```{r}

ls()
Sys.time()
gc()

```
